package Vista;

import Modelo.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Time;

public class JInternalFrameRevista extends javax.swing.JInternalFrame {

    public JInternalFrameRevista() {
        initComponents();
        jTextnumero.setEnabled(false);//Deshabilitar campo de numero
    }

    public void LimpiarCampos() {
        jTextnumero.setText("");
        jTexttitulo.setText("");
        jTextayo.setText("");
        jTextissn.setText("");
        jTextprecio.setText("");
        jTexthoraventa.setText("");
    }

    //Metodo para listar datos dentro de la tabla
    public void obtenerDatos() {
        //se crea una lista que almacena los datos obtenidps
        List<Revista> revistas = new DAORevista().ObtenerDatos();
        //Define un Modelo para la tabla
        DefaultTableModel modelo = new DefaultTableModel();
        //Arreglo con nombres de columnas de la tabla
        String[] columnas = {"Numero", "Titulo", "año", "Issn", "Precio", "Horaventa"};
        //Establece los nombres definidos de la columnah
        modelo.setColumnIdentifiers(columnas);
        for (Revista rev : revistas) { //Recorre cada elemento de la lista y los agrega
            //al modelo de la tabla
            String[] renglon = {Integer.toString(rev.getNumero()), rev.getTitulo(),
                Integer.toString(rev.getAyo()), rev.getIssn(),
                Float.toString(rev.getPrecio()),
                rev.getHoraventa().toString()};
            modelo.addRow(renglon);
        }
        jTableRevista.setModel(modelo);//Ubica los datos del modelo en la tabla
    }

    public void actualizarRevista() {
        int num = Integer.parseInt(this.jTextnumero.getText());
        String titu = jTexttitulo.getText();
        int ay = Integer.parseInt(this.jTextayo.getText());
        String iss = jTextissn.getText();
        float pre = Float.parseFloat(this.jTextprecio.getText());
        Time hrv = Time.valueOf(this.jTexthoraventa.getText());

        DAORevista dao = new DAORevista();
        int res = dao.Actualizar(num, titu, ay, iss, pre, hrv);
        if (res == 1) {
            JOptionPane.showMessageDialog(rootPane, "¡Revista actualizada!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "¡Ocurrio un error!");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAutor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextnumero = new javax.swing.JTextField();
        jTexthoraventa = new javax.swing.JTextField();
        jTexttitulo = new javax.swing.JTextField();
        jTextissn = new javax.swing.JTextField();
        jTextprecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextayo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jBAgregarR = new javax.swing.JButton();
        jBBorrarR = new javax.swing.JButton();
        jBEditarR = new javax.swing.JButton();
        jBActualizarR = new javax.swing.JButton();
        jTextBusqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRevista = new javax.swing.JTable();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Autores Registrados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel3.setLayout(new javax.swing.OverlayLayout(jPanel3));

        jTableAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTableAutor);

        jPanel3.add(jScrollPane1);

        setClosable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar / Actualizar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Numero");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Titulo");

        jLabel3.setForeground(new java.awt.Color(0, 0, 102));

        jLabel4.setForeground(new java.awt.Color(0, 0, 102));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("HoraVenta");

        jTextnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnumeroActionPerformed(evt);
            }
        });

        jTexthoraventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexthoraventaActionPerformed(evt);
            }
        });

        jTexttitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexttituloActionPerformed(evt);
            }
        });

        jTextprecio.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Año");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Precio");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Issn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextayo, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextissn, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexthoraventa, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTexttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextayo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextissn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jTextprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTexthoraventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transacciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        jBAgregarR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBAgregarR.setForeground(new java.awt.Color(0, 0, 102));
        jBAgregarR.setText("Agregar");
        jBAgregarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarRActionPerformed(evt);
            }
        });

        jBBorrarR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBBorrarR.setForeground(new java.awt.Color(0, 0, 102));
        jBBorrarR.setText("Borrar");
        jBBorrarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarRActionPerformed(evt);
            }
        });

        jBEditarR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBEditarR.setForeground(new java.awt.Color(0, 0, 102));
        jBEditarR.setText("Editar");
        jBEditarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarRActionPerformed(evt);
            }
        });

        jBActualizarR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBActualizarR.setForeground(new java.awt.Color(0, 0, 102));
        jBActualizarR.setText("Actualizar");
        jBActualizarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarRActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextBusqueda)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBEditarR, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jBActualizarR)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBBorrarR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAgregarR, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jBAgregarR)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEditarR)
                    .addComponent(jBActualizarR))
                .addGap(18, 18, 18)
                .addComponent(jBBorrarR)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(13, 13, 13)
                .addComponent(jTextBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Revista/Registradas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel4.setLayout(new javax.swing.OverlayLayout(jPanel4));

        jTableRevista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(jTableRevista);

        jPanel4.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarRActionPerformed
        // Captura  datos de la caja de texto
        String titu = jTexttitulo.getText();
        int ay = Integer.parseInt(this.jTextayo.getText());
        String iss = jTextissn.getText();
        float pre = Float.parseFloat(this.jTextprecio.getText());
        String hrv = jTexthoraventa.getText();
        //Comprueba que las cajas  de texto no esten vacias
        if (titu.contentEquals("") || Integer.toString(ay).contentEquals("")
                || iss.contentEquals("") || Float.toString(pre).contentEquals("")
                || hrv.contentEquals("")) {

            JOptionPane.showMessageDialog(rootPane,
                    "Todos los campos son obligatorios");
        } else {

            try {

                Time hrvTime = Time.valueOf(hrv); // Convierte el String a Time
                // Objeto para acceder al método Insertar de DAORevista
                Revista rev = new DAORevista().Insertar(titu, ay, iss, pre, hrvTime);
                JOptionPane.showMessageDialog(rootPane, "Registro agregado");

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "No se agrego el registro");

            }
        }
        obtenerDatos(); //llama a este metodo para que se muestre el nuevo
        // registro en la tabla de formularios
        LimpiarCampos();

    }//GEN-LAST:event_jBAgregarRActionPerformed

    private void jBBorrarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarRActionPerformed
        int fila = this.jTableRevista.getSelectedRow();
        if (fila == 1) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
        } else {
            int num = Integer.parseInt((String) this.jTableRevista.getValueAt(fila, 0).toString());
            DAORevista dao = new DAORevista();
            dao.Eliminar(num);
            obtenerDatos();
        }

    }//GEN-LAST:event_jBBorrarRActionPerformed

    private void jBEditarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarRActionPerformed
        int fila = this.jTableRevista.getSelectedRow(); //Se obtiene filas seleccionadas
        // y se asigna a una variable
        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
        } else { //Se toma cada campo de la tabla del registro seleccionado
            // y se asigna una variable
            try {
                int id = Integer.parseInt((String) this.jTableRevista.getValueAt(fila, 0).toString());
                String titu = (String) this.jTableRevista.getValueAt(fila, 1);
                String ay = (String) this.jTableRevista.getValueAt(fila, 2);
                String iss = (String) this.jTableRevista.getValueAt(fila, 3);
                String pre = (String) this.jTableRevista.getValueAt(fila, 4);
                Time hrv = Time.valueOf((String) this.jTableRevista.getValueAt(fila, 5).toString());

                //Se ubican en las cajas de textos los datos capturados de la tabla
                jTextnumero.setText("" + id);
                jTexttitulo.setText(titu);
                jTextayo.setText(ay);
                jTextissn.setText(iss);
                jTextprecio.setText(pre);
                jTexthoraventa.setText(String.valueOf(hrv));
            } catch (NumberFormatException e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_jBEditarRActionPerformed

    private void jBActualizarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarRActionPerformed
        actualizarRevista();
        obtenerDatos();
        LimpiarCampos();

    }//GEN-LAST:event_jBActualizarRActionPerformed

    private void jTextnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnumeroActionPerformed

    private void jTexttituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexttituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexttituloActionPerformed

    private void jTexthoraventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexthoraventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexthoraventaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Obtiene el texto ingresado en el campo de búsqueda
        String terminoBusqueda = jTextBusqueda.getText().trim();

// Valida que el campo de búsqueda no esté vacío
        if (terminoBusqueda.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese un término para buscar."); // Muestra un mensaje al usuario si el campo está vacío
            return; // Finaliza el método
        }

        try {
            // Determina el criterio de búsqueda basado en una selección previa (por ejemplo, un comboBox)
            String criterio =  jTextBusqueda.toString(); // Se asume que existe un comboBox para seleccionar el criterio
            String valor = terminoBusqueda;

            // Llama al método Buscar en DAORevista para obtener la lista de revistas que coinciden con el criterio y valor de búsqueda
            List<Revista> revistas = new DAORevista().Buscar(criterio, valor);

            // Valida si hay resultados en la lista de revistas
            if (revistas.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "No se encontraron revistas con el término: " + terminoBusqueda); // Informa al usuario que no hubo coincidencias
                return; // Finaliza el método
            }

            // Crea un modelo para la tabla con las columnas especificadas
            DefaultTableModel modelo = new DefaultTableModel();
            String[] columnas = {"Número", "Título", "Año", "ISSN", "Precio", "Hora de Venta"};
            modelo.setColumnIdentifiers(columnas); // Configura los nombres de las columnas en el modelo

            // Recorre la lista de revistas y las agrega como filas al modelo
            for (Revista rev : revistas) {
                String[] renglon = {
                    String.valueOf(rev.getNumero()), // Convierte el número a String
                    rev.getTitulo(), // Obtiene el título de la revista
                    String.valueOf(rev.getAyo()), // Convierte el año a String
                    rev.getIssn(), // Obtiene el ISSN de la revista
                    String.valueOf(rev.getPrecio()), // Convierte el precio a String
                };
                modelo.addRow(renglon); // Agrega la fila al modelo
            }

            // Actualiza la tabla con el modelo que contiene los datos de las revistas encontradas
            jTableRevista.setModel(modelo);

        } catch (Exception e) {
            e.printStackTrace(); // Muestra detalles del error en la consola
            JOptionPane.showMessageDialog(rootPane, "Ocurrió un error al realizar la búsqueda."); // Notifica al usuario sobre el error
        }


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizarR;
    private javax.swing.JButton jBAgregarR;
    private javax.swing.JButton jBBorrarR;
    private javax.swing.JButton jBEditarR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAutor;
    private javax.swing.JTable jTableRevista;
    private javax.swing.JTextField jTextBusqueda;
    private javax.swing.JTextField jTextayo;
    private javax.swing.JTextField jTexthoraventa;
    private javax.swing.JTextField jTextissn;
    private javax.swing.JTextField jTextnumero;
    private javax.swing.JTextField jTextprecio;
    private javax.swing.JTextField jTexttitulo;
    // End of variables declaration//GEN-END:variables
}
